### ISSUE TITLE
Im getting the `Exception while invoking method 'MeteorToys_ia'` with Meteor Toys 2.3.1

### ISSUE THREAD

**Issue by THPubs** [MeteorToys/allthings#64]
Hi, I saw that this issue have been fixed earlier. But I just started to face the issue suddenly.

```
I20151208-14:12:41.413(5.5)? Exception while invoking method 'MeteorToys_ia' TypeError: Cannot read property 'username' of null
I20151208-14:12:41.413(5.5)?     at [object Object].Meteor.(anonymous function).MeteorToys_ia (packages/meteortoys_authenticate/server/methods.js:1:1)
I20151208-14:12:41.413(5.5)?     at packages/check/match.js:103:1
I20151208-14:12:41.413(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151208-14:12:41.413(5.5)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:102:1)
I20151208-14:12:41.413(5.5)?     at maybeAuditArgumentChecks (livedata_server.js:1695:18)
I20151208-14:12:41.413(5.5)?     at livedata_server.js:708:19
I20151208-14:12:41.413(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151208-14:12:41.413(5.5)?     at livedata_server.js:706:40
I20151208-14:12:41.413(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151208-14:12:41.413(5.5)?     at livedata_server.js:704:46
```

I can see this error repeating in the shell and the browser console. Please help.

**Comment by THPubs** [comment]
Found the cause! Whenever a user login, I logout all the other sessions of that user with this :

```
Meteor.logoutOtherClients();
```

When this is removed, the error will disappear! Can we fix that?

**Comment by onedr0p** [comment]
+1 I am having this issue, meteor toys won't show up :(

**Comment by msavin** [comment]
Are you guys on the latest version? I thought this was fixed earlier.

May I suggest: remove and re-add Meteor Toys. If the issue persists, please send me your package list.

**Comment by onedr0p** [comment]
Actually my issue was very strange, and I don't know if it's mentioned anywhere. But the order in which you place `meteortoys:allthings` in the `.meteor/package` file depends on if it works or not. In my case I had it at the bottom. I moved it up near the top and all is good.

**Comment by aaronjudd** [comment]
I am also getting this regardless of placement of the package in .meteor/packages, or add/remove. `meteor list` shows `meteortoys:allthings                       2.3.1  Insanely Handy Development Tools`

**Comment by onedr0p** [comment]
My guess is still a package conflict. Try enabling / disabling them.

**Comment by KyleKing** [comment]
Solved: Turns out this is not Meteor toys! But something else. I've been developing without Meteor toys and started to get the same issue

## 

## 

## 

I get the same issue as well. Whenever I refresh my browser, I automatically get logged out of my app. I tried removing and re-adding Velocity, Kadira, all of my personal packages, and meteortoys with no success. If you want to try replicating my issue, my app is public at: https://github.com/KyleKing/TeamBIKES

```
I20160228-14:38:32.908(-5)? Exception while invoking method 'MeteorToys_ia' TypeError: Cannot read property 'username' of null
I20160228-14:38:32.909(-5)?     at [object Object].Meteor.(anonymous function).MeteorToys_ia (/Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/packages/meteortoys_authenticate.js:19:1302)
I20160228-14:38:32.909(-5)?     at [object Object].methodMap.(anonymous function) (/Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2722:30)
I20160228-14:38:32.909(-5)?     at maybeAuditArgumentChecks (/Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/packages/ddp-server.js:1785:12)
I20160228-14:38:32.909(-5)?     at /Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/packages/ddp-server.js:872:20
I20160228-14:38:32.910(-5)?     at [object Object]._.extend.withValue (/Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/packages/meteor.js:1021:17)
I20160228-14:38:32.910(-5)?     at /Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/packages/ddp-server.js:871:41
I20160228-14:38:32.910(-5)?     at [object Object]._.extend.withValue (/Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/packages/meteor.js:1021:17)
I20160228-14:38:32.911(-5)?     at /Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/packages/ddp-server.js:870:46
I20160228-14:38:32.911(-5)?     at tryCallTwo (/Users/kyleking/.meteor/packages/promise/.0.5.1.qtl00++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20160228-14:38:32.911(-5)?     at doResolve (/Users/kyleking/.meteor/packages/promise/.0.5.1.qtl00++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20160228-14:38:32.911(-5)?     at new Promise (/Users/kyleking/.meteor/packages/promise/.0.5.1.qtl00++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
I20160228-14:38:32.911(-5)?     at [object Object]._.extend.protocol_handlers.method (/Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/packages/ddp-server.js:848:21)
I20160228-14:38:32.912(-5)?     at /Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2610:38
I20160228-14:38:32.912(-5)?     at [object Object]._.extend.withValue (/Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/packages/meteor.js:1021:17)
I20160228-14:38:32.912(-5)?     at [object Object].sessionProto.protocol_handlers.method (/Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2609:44)
I20160228-14:38:32.912(-5)?     at /Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/.meteor/local/build/programs/server/packages/ddp-server.js:729:85
```

My packages are:

``` coffee
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

# autopublish             # Publish all data to the clients (for prototyping)
# insecure                # Allow all DB writes from clients (for prototyping)

meteortoys:allthings # press ctrl-m to activate

### Routing ###
kadira:flow-router
philippspo:momentum-flow-router # page-transitions
kadira:blaze-layout # for page Rendering
arillo:flow-router-helpers # for pathFor
zimme:active-route # for isActiveRoute
# HTTPS
spiderable
force-ssl

#### Authentication ####
accounts-password
alanning:roles
useraccounts:bootstrap
useraccounts:flow-routing

#### Preprocessors ####
mquandalle:jade
coffeescript
stolinski:stylus-multi # with postCSS support! but somewhat outdated elsewhere

#### Visual Things ####
kyleking:customizable-bootstrap-stylus
fortawesome:fontawesome
timmyg:wow # animation library
# natestrauser:animate-css
juliancwirko:s-alert # Banner alerts
juliancwirko:s-alert-stackslide # animation style

#### Tools ####
mrt:underscore-string-latest # Lots of functions
momentjs:moment # Date and Time
aldeed:moment-timezone

### Maps ###
bevanhunt:leaflet
appshore:leaflet-awesome-markers
herrhelms:meteor-leaflet-locatecontrol
fuatsengul:leaflet-easybutton

### Data ###
kyleking:tabular # data tables
kyleking:tabular-column-search
# kidovate:bootstrap-slider # input slider
# d3js:d3

### Seed Data ###
dburles:factory
anti:fake

#### Collection Management ####
jagi:astronomy
jagi:astronomy-validators

### Performance Monitoring ###
meteorhacks:kadira # server
kadira:debug # local/client
percolate:synced-cron # Timing for bike rentals and email verification
email

#### Mobile Functions ####
# mdg:camera

### Preventing Regression ###
sanjo:jasmine
velocity:html-reporter
velocity:console-reporter
```

Also:

```
$ meteor list
meteortoys:allthings                    2.3.1  Insanely Handy Development Tools
```

**Comment by ipa1981** [comment]
Have the same issue. On user logout I get such error on server.
meteortoys:allthings          2.3.1  Insanely Handy Development Tools

**Comment by acomito** [comment]
I am also getting this issue:

```
Exception while invoking method 'MeteorToys_ia' { stack: 'TypeError: Cannot read property \'username\' of null\n    at [object Object].Meteor.(anonymous function).MeteorToys_ia (packages/meteortoys_authenticate/server/methods.js:1:1)\n    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)\n    at maybeAuditArgumentChecks (livedata_server.js:1698:12)\n    at livedata_server.js:708:19\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at livedata_server.js:706:40\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at livedata_server.js:704:46\n    at tryCallTwo (/Users/MyName/.meteor/packages/promise/.0.5.1.17lemgp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)\n    at doResolve (/Users/MyName/.meteor/packages/promise/.0.5.1.17lemgp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)',
I20160325-15:20:42.315(-4)?   source: 'method' }
```

**Comment by dortega3000** [comment]
Same here!!! 
Exception while invoking method 'MeteorToys_ia' TypeError: Cannot read property 'address' of undefined

**Comment by MichaelJCole** [comment]
```
if (Meteor.isClient) {
  // onLogin, set the active tab to our tabToken
  Accounts.onLogin(function() {
    Accounts.logoutOtherClients();
  });
}
```

I'm also getting this error in the code above.

Had to solve by removing meteor toys package.  Would be cool to have both.

**Comment by msavin** [comment]
Cool - I've been using Accounts.onLogin, which I suspect may have caused some of the issues. I'm now using a different approach which should hopefully sidestep this problem. New version coming soon.

**Comment by felixb101** [comment]
I use Meteor.logout() and I get the error ...

**Comment by msavin** [comment]
This issue has been resolved in Meteor Toys 3, and your new activation code should be in your inbox. Please upgrade and let me know how it works. If you experience any issues, please open a new issue.

**Comment by rojour** [comment]
I'm still having the same issue... and I did not had Meteor toys installed. I did installed it and the problem is still there.

**Comment by msavin** [comment]
Hmm are you sure you have the latest MT package?

**Comment by rojour** [comment]
I do... but I may have some other issue with my code. I will work on that on Monday. I'll let you know...
By the way, the package is pretty cool and even more that you are on top of it.
Thanks

**Comment by rojour** [comment]
Now I can confirm that I had an error in my code and its all good now. Thank you.
